spring.application.name=standup-ai
# Server
server.port=8080

# Database
#spring.datasource.url=jdbc:mySql://localhost:3306/hackathon
spring.datasource.username=root
spring.datasource.password=Adapa@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=InnoCito-StandUp-AI-2024-JWT-Super-Secret-Key-With-Minimum-256-Bits-For-HS256-Algorithm-Security
jwt.expiration=86400000

# Gemini AI
#spring.ai.gemini.chat.options.model=gemini-pro

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=madapa@gitam.in
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.com.innocito.standupai=DEBUG

allowed.domains=innocito.com

